project:
  type: website

website:
  description: "TJ Palanca"
  site-url: https://docs.tjpalanca.com
  title: "TJ Palanca"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tjpalanca
      - icon: twitter
        href: https://x.com/tjpalanca
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



